### ISSUE TITLE
Support builtin type as value

### ISSUE THREAD

**Issue by tristan0x** [cogniteev/yamlious#1]
In 0.1.3, it not possible to easily represent the following voluptuous expression:

```python
Schema({
  Required('foo'): string
}
```

The simplest way to do it with yamlious is:

```yaml
foo:
    key: Required
    All:
        - string
```

The `All` function is useless, the following yamlious expression should be valid:

```yaml
foo:
    key: Required
    string:
```
